### ISSUE TITLE
Summary message for stFLIP

### ISSUE THREAD

**Issue by ZiggStardust** [CumpsD/chainflip-insights#21]
**Add a Summary of StakedFLIP Mints**

**Message format** 

"x FLIP staked to stFLIP @ stakedflip.fi in the past 24 Hours"

**Message Schedule** 

Every 6 hours  

**Data source**

- https://thegraph.com/hosted-service/subgraph/thunderhead-labs/stakedflip-omega-subgraph

Example 
```
curl 'https://api.thegraph.com/subgraphs/name/thunderhead-labs/stakedflip-omega-subgraph' \
  -H 'accept: application/json, multipart/mixed' \
  --data-raw '{"query":"{\n  mints(first:1000, where:{ blockTimestamp_gt: 1710088461 }) {\n    amount\n  }\n}"}'
  ```

**Comment by ZiggStardust** [comment]
If we could have an alert on a big stake aswell - above 50k that would be great :)

**Comment by CumpsD** [comment]
Query for a day:
```
{
    mints(orderBy: blockTimestamp, where: { 
        blockTimestamp_gte: 1710892800,
        blockTimestamp_lt: 1710979200
    }) {
        id
        blockNumber
        blockTimestamp
        amount
        to
        transactionHash
    }
}
```

**Comment by CumpsD** [comment]
> If we could have an alert on a big stake aswell - above 50k that would be great :)

Following this in https://github.com/CumpsD/chainflip-insights/issues/32

**Comment by CumpsD** [comment]
Example: https://twitter.com/ChainflipBot/status/1771329739627593737
