### ISSUE TITLE
Show Affiliate Brokers [300 FLIP]

### ISSUE THREAD

**Issue by CumpsD** [CumpsD/chainflip-insights#67]
# Show Affiliate Brokers

## Scope

Everywhere broker information is used, display the involved affiliate brokers as well instead of just the main broker.

## More Info

```graphql
{
    allSwaps(orderBy: ID_ASC, first: 500, filter: {
        id: { greaterThan: 10235 }
        }) {
        edges {
            node {
                id
                nativeId
                type
                swapScheduledBlockTimestamp

                depositAmount
                depositValueUsd
                sourceAsset
                sourceChain

                egressAmount
                egressValueUsd
                destinationAsset
                destinationChain
                destinationAddress

                intermediateAmount
                intermediateValueUsd

                swapChannelByDepositChannelId {
                    swapChannelBeneficiariesByDepositChannelId {
                        nodes {
                            brokerCommissionRateBps
                            type
                            brokerByBrokerId {
                                accountByAccountId {
                                    idSs58
                                }
                            }
                        }
                    }
                    brokerByBrokerId {
                        accountByAccountId {
                            idSs58
                        }
                    }
                }
            }
        }
    }
}
```

## Bounty

FLIP required for development: **300 FLIP**
To start development, send the bounty to **0x2578f4fa0f36138c76389095bf74331a4f57bcc0** and comment with a link to the transaction.

**Comment by Haafingar** [comment]
Chainflip Labs will fund this bounty

**Comment by CumpsD** [comment]
> I'll like to work on this

Thanks for the offer, the development of this feature has already been picked up however.

**Comment by CumpsD** [comment]
https://etherscan.io/tx/0x558978922757ae30407258aee1eec00b2f6f9b280d9c2e74cf58eea0c805a6bc

**Comment by CumpsD** [comment]
![Image](https://github.com/user-attachments/assets/e91d2f10-a2b9-41f7-8bb5-81fb9223d51c)

Babylon is an Affiliate broker and now shows up in swaps.

Waiting for broker daily overview to get announced to display affiliate brokers there as well.
