### ISSUE TITLE
Provide summary of highest LPs per day/week [400 FLIP]

### ISSUE THREAD

**Issue by CumpsD** [CumpsD/chainflip-insights#84]
# Show top liquidity providers per day/week

## Scope

Every day, announce the top LPs

Every week provide a summary of the top 5 LPs.

## More Info

Find a way to count LP activity per day, perhaps based of diffing the overal volume on timer.

## Bounty

FLIP required for development: **400 FLIP**
To start development, send the bounty to **0x2578f4fa0f36138c76389095bf74331a4f57bcc0** and comment with a link to the transaction.

**Comment by Haafingar** [comment]
Chainflip Labs will fill this bounty

**Comment by Haafingar** [comment]
Would be cool to show the:
Volume share as a percentage
Total liquidity controlled by the LP at the snapshot time
Labels for the LPs
Aggregate the accounts of LPs who use multiple on-chain accounts (we can help with this) to get a more holistic picture of the different actors

**Comment by CumpsD** [comment]
https://etherscan.io/tx/0x558978922757ae30407258aee1eec00b2f6f9b280d9c2e74cf58eea0c805a6bc

**Comment by CumpsD** [comment]
Daily

Discord
![Image](https://github.com/user-attachments/assets/608a3b13-618a-4b39-9148-67fa28026c27)

TG
![Image](https://github.com/user-attachments/assets/d6a6380e-2441-47c9-a518-4879780ed952)

Twitter
![Image](https://github.com/user-attachments/assets/9e66f3fa-3242-4ea4-b325-55b95887e137)

**Comment by CumpsD** [comment]
Weekly

Discord
![Image](https://github.com/user-attachments/assets/4ec7b33f-596f-490c-9a01-0e3f7a206103)

TG
![Image](https://github.com/user-attachments/assets/18870103-0dc8-4113-ad73-f38d2c4732d5)

Twitter
![Image](https://github.com/user-attachments/assets/c555619a-5aa4-45ac-9266-fd1c54e22362)

Mastodon
![Image](https://github.com/user-attachments/assets/47d303d7-619c-4e97-80cc-ea25a046df37)

**Comment by CumpsD** [comment]
Open todo's:
Total liquidity controller by LP
% of total volume

**Comment by CumpsD** [comment]
Add fees too? the 0.05% LP fee at least, even though with spreads they can earn even more

**Comment by CumpsD** [comment]
% are in, visible on next announcement

**Comment by CumpsD** [comment]
![Image](https://github.com/user-attachments/assets/fc3895b2-3f5e-48bf-83ec-4bbbc1feb60a)
